Изменил главную страницу сайта
htmlacademy-php/1658553-readme-12 pull request #15
Opened 2021-12-03 12:59 UTC by Dzoter

ограничил просмотр сайта только для зарегистрированных пользователей, добавил валидацию на вход, добавил возможность выхода с сайта(закрытие сессии), немного наполнил страницу feed.php информацией из данных сессии.

2021-12-09 08:09 UTC, ademaro commented on add.php
> +if (empty($_SESSION)) {
в сессии мы можем хранить не только авторизацию, давай что-то типа if ($is_auth) использовать

2021-12-09 08:11 UTC, ademaro commented on add.php
> +    );
как-то готовишь шаблоны на все случаи сразу, может, рендерить только то, что нужно сейчас?

2021-12-09 08:12 UTC, ademaro commented on feed.php
> +session_start();
это в конфиг или инит какой-нибудь, у нас на всех страницах практически работа с сессиями

2021-12-09 08:12 UTC, ademaro commented on feed.php
> +const PAGE_FEED = '/1658553-readme-12/feed.php';
хм, странный путь, давай поправим

2021-12-09 08:14 UTC, ademaro commented on popular.php
> +const PAGE_POPULAR = '/1658553-readme-12/popular.php';
у меня в кофигурации может быть совсем другой путь быть, подумай как делать проверку более универсально

2021-12-09 08:15 UTC, ademaro commented on post.php
> +    $postId = retriveGetInt('post-id', 0);
что за 0?

2021-12-09 08:16 UTC, ademaro commented on post.php
> +        $commentAllList = commentList($mysql, $postId, 0, 200);
что за 0 и 2 и 200? commentList — название с глаголом должно быть

2021-12-09 08:18 UTC, ademaro commented on src/function.php
> +function layoutContentDefine()
странная функция, видел проверку ты делаешь напрямую. Либо тогда используй везде эту функцию

2021-12-09 08:18 UTC, ademaro commented on src/function.php
> +    } else {
else не нужен, если выше return

2021-12-09 08:24 UTC, ademaro commented on src/validate.php
> +function singUpEmail(string $email, mysqli $mysql)
checkErrorSignUpEmail -> false в случае отсутствия ошибок или ошибка (которая будет true, если будет проверять) и не надо будет использовать is_bool

2021-12-09 08:30 UTC, ademaro commented on src/validate.php
> +    $userEmail = $_POST['email'];
не бери напрямую из $_POST, передавай значение

2021-12-09 08:31 UTC, ademaro commented on src/validate.php
> +function singUpPassword(string $password, mysqli $mysql)
обрати внимание на порядок параметров, сделай единообразно, например, link к БД — всегда первым

2021-12-09 08:32 UTC, ademaro commented on src/validate.php
> +    $hashPassword = password_verify($password, $userInfo[0]['password']);
индекс 0 говорит, что что-то не то) выбирай через fetch_row, а не fetch_all

2021-12-09 08:33 UTC, ademaro requested changes
оставляю открытым ПР, жду правок, в целом хороший прогресс, молодец!

2021-12-10 13:22 UTC, Dzoter commented on add.php
> +if (empty($_SESSION)) {
Исправил

2021-12-10 13:22 UTC, Dzoter commented on add.php
> +    );
исправил

2021-12-10 13:22 UTC, Dzoter commented on feed.php
> +session_start();
исправил

2021-12-10 13:22 UTC, Dzoter commented on feed.php
> +const PAGE_FEED = '/1658553-readme-12/feed.php';
исправил

2021-12-10 13:23 UTC, Dzoter commented on popular.php
> +const PAGE_POPULAR = '/1658553-readme-12/popular.php';
исправил

2021-12-10 13:23 UTC, Dzoter commented on post.php
> +    $postId = retriveGetInt('post-id', 0);
Я реиспользовал эту функцию. Она используется в другом месте и принимает в себя null(для типов контента) 
Я поставил 0 для следующего:
Если в адресной строке просмотра постов будет НЕ цифра, а например строка, то по умолчанию пользователя будет направлять на 0 id поста, который отсутствует и перенаправит на стр.  которая скажет, что такой стр нет. Я мог бы написать новую функцию, но я стараюсь реиспользовать старые, что бы было меньше кода  по принципу DRY

2021-12-10 13:23 UTC, Dzoter commented on post.php
> +        $commentAllList = commentList($mysql, $postId, 0, 200);
Нейминг я исправил, однако касательно limit и offset- Функционал на сайте следующий, по умолчанию максимум комментов для отображения-2 По этому тут и подключаются лимиты и офсеты. Если комментариев больше двух то появляется плашка с предложением посмотреть все комментарии, я лимитировал до 200 потому что в тз не написано максимальное значение, да и пагинации нет для комментариев

2021-12-10 13:26 UTC, Dzoter commented on src/function.php
> +function layoutContentDefine()
Не могу, эта функция возвращает 2 класса HTML в зависимости от стр. feed-лента, имеющая класс page__main--feed.
А популярное page__main--feed. this OR this
Проверку напрямую я провожу с элементами header, там тоже в зависимости от стр, но класс всегда один - header__page-link--active.

2021-12-10 13:27 UTC, Dzoter commented on src/function.php
> +    } else {
добавил elsif т.к. в дальнейшем будет еще стр пользователя, которая будет иметь свой класс

2021-12-10 13:51 UTC, Dzoter commented on src/validate.php
> +function singUpEmail(string $email, mysqli $mysql)
Сделал для всей валидации

2021-12-10 14:02 UTC, Dzoter commented on src/validate.php
> +    $userEmail = $_POST['email'];
Исправил

2021-12-10 14:13 UTC, Dzoter commented on src/validate.php
> +function singUpPassword(string $password, mysqli $mysql)
Исправил

2021-12-10 14:14 UTC, Dzoter commented on src/validate.php
> +    $userEmail = $_POST['email'];
Но хотелось бы узнать, почему так? и только ли из $_POST так нельзя? из каких еще супермассивов нельзя?

2021-12-10 14:14 UTC, Dzoter commented on src/validate.php
> +    $hashPassword = password_verify($password, $userInfo[0]['password']);
исправил

2021-12-15 02:22 UTC, ademaro commented on post.php
> +        $commentAllList = commentList($mysql, $postId, 0, 200);
хорошо бы вынести магические цифры в константы

2021-12-15 02:26 UTC, ademaro commented on src/validate.php
> +    $userEmail = $_POST['email'];
Это не очень универсально, ну например ты захочешь регистрировать пользователя, но не через POST а как-то ещё. Теоретически в POST[email] может попасть совсем не то, что мы ожидаем и тд... Ты в этой функции работаешь с глобальной областью видимости, для этой функции это будет чёрным ящиком, что не очень хорошо)

2021-12-15 02:27 UTC, ademaro commented on src/function.php
> +    } else {
не вижу)

2021-12-26 09:15 UTC, ademaro approved these changes
Большой рефакторинг, давай дальше пока, буду ждать поправок в следующем ПР отдельным коммитом

2021-12-26 09:15 UTC, ademaro commented on add-comment.php
> +        'comment-text' => [
commentText тогда уж?

2021-12-26 09:15 UTC, ademaro commented on add-comment.php
> +            },
в чём смысл этих валидаций, если всегда false?

2021-12-26 09:15 UTC, ademaro commented on add-comment.php
> +        'comment-text' => [
остальные поля — так же

2021-12-26 09:15 UTC, ademaro commented on index.php
> +    header('location: feed.php');
а если мы откроем вручную feed.php —  редиректимся на логин?) Если не авторизованы

2021-12-26 09:15 UTC, ademaro commented on model/models.php
> +    } else {
else в таких случаях не нужен

2021-12-26 09:15 UTC, ademaro commented on model/models.php
> +    } else {
почисти везде

2021-12-26 09:15 UTC, ademaro commented on search.php
> +            'block' => $searchBLock,
searchBLock -> searchBlock

2021-12-26 09:15 UTC, ademaro commented on src/add-query.php
> +function addCite(mysqli $mysql, $key, int $lastPostId): int
что такое $key? описывай сразу в phpDoc

2021-12-26 09:15 UTC, ademaro commented on src/add-query.php
>      $queryPost = "UPDATE post SET text_content = '$content', content_type_id = '$contentType' WHERE id = '$lastPostId'";
давай мигрировать на подготовленные выражения или делай либо хотя бы https://www.php.net/manual/ru/function.mysql-real-escape-string.php
Что бы  не было sql-inj

2021-12-26 09:15 UTC, ademaro commented on src/function.php
> +    }
у тебя же могут поменяться идентификаторы, зачем ты так зашиваешь их? подумай как сделать универсально

2021-12-26 09:15 UTC, ademaro commented on src/function.php
> +            return 'adding-post__link tabs__content--active';
тут так же

2021-12-26 09:16 UTC, merged